### ISSUE TITLE
About the merging with the fork

### ISSUE THREAD

**Issue by Aceship** [graueneko/graueneko.github.io#1]
Thanks for the email about the joint project, i kinda wanted to merge it too, but i dont know how to approach.

as the problem on current fork, the akhr.json are manually translated from the `appelation` on `character_table.json` on the ArknightsGameData, so there is no chinese name on the fork.

are the akhr.json are automatically created from the `character_table.json` ?
if possible, adding the appelation could make it fast for translation on update

**Comment by gneko** [comment]
I merged your works by adding en-{page}.{ext}, now it looks like this, every page has a language switch on top right. You can try on [https://graueneko.github.io/en-akhr.html](https://graueneko.github.io/en-akhr.html).

Your works did a lot for those don't speak chn, like tips and translations in data, and I can't simply migrate them to mine. Since that I started doubting whether it's necessary to merge : (  

Do u have any idea?

**Comment by gneko** [comment]
Noticed your multilingual json files in [https://github.com/Aceship/AN-EN-Tags/tree/master/json](https://github.com/Aceship/AN-EN-Tags/tree/master/json), that's really better than my plan, well done!

**Comment by Aceship** [comment]
Currently we are trying to make a multilanguage per page, probably it takes time before completed 
that way it would easier to update per page instead

**Comment by gneko** [comment]
[https://graueneko.github.io/aklevel.html?lang=en](https://graueneko.github.io/aklevel.html?lang=en) I finished the multilingual on aklevel.html (for it needs only words translation) using `class="cn"` & `class="en"` switch. Maybe this is the simplest & scalable way on a single static page.

**Comment by gneko** [comment]
... and now I finished [https://graueneko.github.io/akhr.html?lang=en](https://graueneko.github.io/akhr.html?lang=en) using your image codes and translations. 

My basic idea is to implement texts in all langs with respective language class, so that it's easy to show required language using js & jquery. Visitors request with `?lang=cn` or `?lang=en` parameter to specify wanted text.

Remaining works left mainly on the chars data, it's a huge work.

**Comment by Aceship** [comment]
the current one we are working with are with selection for multi region server (in case other language server are opened) to their choice of language and the tags are also from json, so its easier to update from json instead from the html, so it takes more time to make 

![image](https://user-images.githubusercontent.com/5337323/57233450-db41f580-7048-11e9-980b-b3f6473f3912.png)

**Comment by Faryzal2020** [comment]
i've completed the initial process of the whole implementation on switchable language without refreshing the page, should have some bugs. 
so the idea is that the "game server" dropdown switches the language of the tag selections and the tooltip text on the generated results, because jp and kr version should have different writing. 
And then the "translate to" dropdown translates all the other stuffs to the desired language, those stuffs including:
- Tooltip texts on the tags selection (done)
- UI texts like "select the tags" (currently not done yet)
- operator names and tag names (done)
![image](https://user-images.githubusercontent.com/8612170/57249455-f7ad5480-707f-11e9-8ef7-03a41ab697f0.png)

edit: i'm planning to add another json file as the glossary for the UI texts that stores the text translation for each languages. Not only that this would make things easier and tidier for me, this also allows us or even other people to contribute and add more languages other than en, jp, and kr if they need one.

**Comment by Aceship** [comment]
After some time , probably its best to not merge, i think its better to have 2 different type since there's too many different thing made inbetween (especially change language system and theme), and tons of feature are made differently

thanks for the invitation to merge the page, we'll continue translating stuff on our commit in case you need some of the files

**Comment by gneko** [comment]
Same, I think it's better to keep different repos for too many differences. 

Thanks for your images and works. You can also keep track of my following works ; ) Have fun with Arknights game.
